version: "3.4"

x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Lor3mDimpsum

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  db:
    build: ./db
    image: postgres:14.6-alpine3.17
    DB_HOST_NAME: db.mfjuoqtfvjvffckuzdri.supabase.co
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: Lor3mDimpsum
    DB_NAME: postgres
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - "pg_${PLAID_ENV}_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment: *common-variables

  server:
    build: ./server
    image: plaidinc/pattern-server:1.0.7
    ports:
      - 5001:5001
    environment:
      <<: *common-variables
      PLAID_CLIENT_ID:
      PLAID_SECRET_SANDBOX:
      PLAID_SECRET_DEVELOPMENT:
      PLAID_SANDBOX_REDIRECT_URI:
      PLAID_DEVELOPMENT_REDIRECT_URI:
      PLAID_ENV:
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: db.mfjuoqtfvjvffckuzdri.supabase.co
    depends_on:
      - db.mfjuoqtfvjvffckuzdri.supabase.co

  ngrok:
    build: ./ngrok
    image: plaidinc/pattern-ngrok:1.0.7
    command: ["ngrok", "http", "server:5001"]
    ports:
      - 4040:4040
    depends_on:
      - server

  client:
    build: ./client
    image: plaidinc/pattern-client:1.0.7
    ports:
      - 3001:3001
    environment:
      REACT_APP_PLAID_ENV: ${PLAID_ENV}
      REACT_APP_SERVER_PORT: 5001
    depends_on:
      - server
